default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>
  username: postgres
  password: rubyway
  host: localhost
  port: 5432
  timeout: 5000

development:
  <<: *default
  database: rubyrary

test:
  <<: *default
  database: rubyrary_test

